import { PageContent } from '../types/content';

export const aboutContent: PageContent = {
  blocks: [
    {
      type: 'hero',
      titleAccent: 'About',
      title: 'us',
      accentColor: 'pink',
      description: 'We are a team of creative professionals dedicated to transforming brands through innovative design and strategic thinking.',
    },
    {
      type: 'grid',
      columns: 3,
      items: [
        {
          title: 'Adventure',
          titleAccent: 'Creative',
          accentColor: 'pink',
          description: 'We serve unique and disruptive brands of all sizes and are fanatical about their success. We explore the impossible of dreams.',
          icon: '/assets/GD-2D/GD-Icon/GD-Icon-014.png',
          background: 'pinkWave',
        },
        {
          title: 'Autonomy',
          titleAccent: 'Design',
          accentColor: 'green',
          description: 'We believe in giving our team the freedom to innovate and create without boundaries.',
          icon: '/assets/GD-2D/GD-Icon/GD-Icon-012.png',
          background: 'greenWave',
        },
        {
          title: 'Excellence',
          titleAccent: 'Client',
          accentColor: 'purple',
          description: 'We strive for excellence in everything we do, ensuring our clients receive the highest quality service.',
          icon: '/assets/GD-2D/GD-Icon/GD-Icon-013.png',
          background: 'purpleWave',
        },
      ],
    },
    {
      type: 'grid',
      title: 'Our Team',
      titleAccent: 'Meet',
      accentColor: 'green',
      columns: 3,
      items: [
        {
          title: 'Creative Art',
          titleAccent: 'Drijke Wessels',
          accentColor: 'purple',
          description: 'Always expanding my knowledge while spreading magic through imagination.',
          image: '/assets/To-Drijke/Bold-Team-Drijke-WB.png',
          background: 'purpleWave',
        },
        {
          title: '3D Modeling',
          titleAccent: 'Kagiso Silindane',
          accentColor: 'yellow',
          description: 'Dedicated to introducing unique skills into animation and art.',
          image: '/assets/wave-yellow.png',
          background: 'yellowWave',
        },
        {
          title: 'Technologist',
          titleAccent: 'Batanayi Matuku',
          accentColor: 'purple',
          description: 'Obsessed with ideating and architecting branding solutions and building bold things for innovative and unique brands.',
          image: '/assets/wave-purple.png',
          background: 'purpleWave',
        },
        {
          title: '3D Artist',
          titleAccent: 'Sibusiso Nkosi',
          accentColor: 'green',
          description: 'Everyday we dream it, we will make it the best we can. If you just think of the job, the credit will automatically follow.',
          image: '/assets/wave-green.png',
          background: 'greenWave',
        },
        {
          title: '3D Animation',
          titleAccent: 'Casey Watson',
          accentColor: 'purple',
          description: 'I am an enthusiastic creative, and am always eager to learn more. Aside from Asset production and animation, I enjoy singing, dancing and acting.',
          image: '/assets/wave-pink.png',
          background: 'purpleWave',
        },
        {
          title: '3D Artist',
          titleAccent: 'Jason Grobler',
          accentColor: 'pink',
          description: 'All creative people want to do the unexpected and the crazy stuff too. I find myself happy with little things like drawing.',
          image: '/assets/wave-pink-wave-5.png',
          background: 'pinkWave',
        },
      ],
    },
    {
      type: 'action',
      theme: 'pink',
      accent: 'darkPink',
      image: '/assets/GD-2D/GD-Icon/GD-Icon-015.png',
      titleAccent: 'Start',
      title: 'your journey',
      description: 'Ready to transform your brand? Let us create something amazing together.',
    },
  ],
};
